export const NotificationsEnums = {
  NO_NOTIFICATION: 0,
  IS_ISSUE_TOKEN: 1,
  IS_SENDING_TOKEN:2,
  TRANSFER_FINISH:21,

  NEED_VALIDATION: 3,
  IS_PROVING:4,

  PROVING_FINISH:5,
  CRETE_ACCESS:6
}
